services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: Paulo99#@

    #Database management interface
  adminer:
      image: adminer:latest
      restart: always
      ports:
        - 8080:8080